version: "3.8"

volumes:
  SmartSchoolDb:

networks:
  InvestmentNet:
  JaegerNet:
  RedisNet:

services:
  jaeger:
    image: "jaegertracing/all-in-one"
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - JaegerNet
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  redis:
    image: redis:6-alpine
    container_name: redis
    ports: 
        - "6379:6379"
    networks: 
        - RedisNet

  investment:
    build:
      context: src/.
      dockerfile: Dockerfile
    container_name: investment
    networks:
      - JaegerNet
      - RedisNet
      - InvestmentNet
    ports:
      - "443:443"
      - "80:80"
